image:
  name: "python:3.12.11"

stages:
  - build
  - test

compile_extension_module:
  stage: build
  before_script:
    - apt update
    - apt install -y python3-dev
    - python3 -m pip install setuptools
    - python3 -m pip install Cython
  script:
    - cd image_manipulation/cynalg
    - python3 setup.py build_ext -i
  artifacts:
    paths:
      - image_manipulation/cynalg/*.so
      - image_manipulation/cynalg/*.c
      - image_manipulation/cynalg/*.html

unittest:
  stage: test
  script:
    - python3 -m pip install pytest
    - python3 -m pip install numpy
    - cd test
    - python3 -m pytest --junitxml=pytest_report.xml linalg_pytest.py
    - echo $?
  artifacts:
    reports:
      junit: test/pytest_report.xml

