# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gimp.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(743, 597)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.graphicsView = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView.setObjectName("graphicsView")
        self.gridLayout_2.addWidget(self.graphicsView, 0, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.loadImageButton = QtWidgets.QPushButton(self.centralwidget)
        self.loadImageButton.setObjectName("loadImageButton")
        self.horizontalLayout_2.addWidget(self.loadImageButton)
        self.showHistogramsButton = QtWidgets.QPushButton(self.centralwidget)
        self.showHistogramsButton.setObjectName("showHistogramsButton")
        self.horizontalLayout_2.addWidget(self.showHistogramsButton)
        self.showScatterPlotsButton = QtWidgets.QPushButton(self.centralwidget)
        self.showScatterPlotsButton.setObjectName("showScatterPlotsButton")
        self.horizontalLayout_2.addWidget(self.showScatterPlotsButton)
        self.gridLayout_2.addLayout(self.horizontalLayout_2, 1, 0, 1, 1)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.tab)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.redFactorNameLabel = QtWidgets.QLabel(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.redFactorNameLabel.sizePolicy().hasHeightForWidth())
        self.redFactorNameLabel.setSizePolicy(sizePolicy)
        self.redFactorNameLabel.setObjectName("redFactorNameLabel")
        self.verticalLayout_2.addWidget(self.redFactorNameLabel)
        self.greenFactorNameLabel = QtWidgets.QLabel(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.greenFactorNameLabel.sizePolicy().hasHeightForWidth())
        self.greenFactorNameLabel.setSizePolicy(sizePolicy)
        self.greenFactorNameLabel.setObjectName("greenFactorNameLabel")
        self.verticalLayout_2.addWidget(self.greenFactorNameLabel)
        self.blueFactorNameLabel = QtWidgets.QLabel(self.tab)
        self.blueFactorNameLabel.setObjectName("blueFactorNameLabel")
        self.verticalLayout_2.addWidget(self.blueFactorNameLabel)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(-1, 20, -1, 15)
        self.verticalLayout.setObjectName("verticalLayout")
        self.redFactorSlider = QtWidgets.QSlider(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.redFactorSlider.sizePolicy().hasHeightForWidth())
        self.redFactorSlider.setSizePolicy(sizePolicy)
        self.redFactorSlider.setMinimum(0)
        self.redFactorSlider.setMaximum(500)
        self.redFactorSlider.setPageStep(0)
        self.redFactorSlider.setProperty("value", 100)
        self.redFactorSlider.setOrientation(QtCore.Qt.Horizontal)
        self.redFactorSlider.setObjectName("redFactorSlider")
        self.verticalLayout.addWidget(self.redFactorSlider)
        self.greenFactorSlider = QtWidgets.QSlider(self.tab)
        self.greenFactorSlider.setMinimum(0)
        self.greenFactorSlider.setMaximum(500)
        self.greenFactorSlider.setSingleStep(1)
        self.greenFactorSlider.setPageStep(0)
        self.greenFactorSlider.setProperty("value", 100)
        self.greenFactorSlider.setOrientation(QtCore.Qt.Horizontal)
        self.greenFactorSlider.setObjectName("greenFactorSlider")
        self.verticalLayout.addWidget(self.greenFactorSlider)
        self.blueFactorSlider = QtWidgets.QSlider(self.tab)
        self.blueFactorSlider.setMinimum(0)
        self.blueFactorSlider.setMaximum(500)
        self.blueFactorSlider.setPageStep(0)
        self.blueFactorSlider.setProperty("value", 100)
        self.blueFactorSlider.setOrientation(QtCore.Qt.Horizontal)
        self.blueFactorSlider.setInvertedAppearance(False)
        self.blueFactorSlider.setObjectName("blueFactorSlider")
        self.verticalLayout.addWidget(self.blueFactorSlider)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.redFactorLineEdit = QtWidgets.QLineEdit(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.redFactorLineEdit.sizePolicy().hasHeightForWidth())
        self.redFactorLineEdit.setSizePolicy(sizePolicy)
        self.redFactorLineEdit.setClearButtonEnabled(False)
        self.redFactorLineEdit.setObjectName("redFactorLineEdit")
        self.verticalLayout_3.addWidget(self.redFactorLineEdit)
        self.greenFactorLineEdit = QtWidgets.QLineEdit(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.greenFactorLineEdit.sizePolicy().hasHeightForWidth())
        self.greenFactorLineEdit.setSizePolicy(sizePolicy)
        self.greenFactorLineEdit.setClearButtonEnabled(False)
        self.greenFactorLineEdit.setObjectName("greenFactorLineEdit")
        self.verticalLayout_3.addWidget(self.greenFactorLineEdit)
        self.blueFactorLineEdit = QtWidgets.QLineEdit(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.blueFactorLineEdit.sizePolicy().hasHeightForWidth())
        self.blueFactorLineEdit.setSizePolicy(sizePolicy)
        self.blueFactorLineEdit.setClearButtonEnabled(False)
        self.blueFactorLineEdit.setObjectName("blueFactorLineEdit")
        self.verticalLayout_3.addWidget(self.blueFactorLineEdit)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget.addTab(self.tab_2, "")
        self.gridLayout_2.addWidget(self.tabWidget, 2, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 743, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.loadImageButton.clicked.connect(MainWindow.on_load_image_button_clicked)
        self.redFactorSlider.sliderReleased.connect(MainWindow.on_color_brightness_slider_released)
        self.greenFactorSlider.sliderReleased.connect(MainWindow.on_color_brightness_slider_released)
        self.blueFactorSlider.sliderReleased.connect(MainWindow.on_color_brightness_slider_released)
        self.redFactorSlider.valueChanged['int'].connect(MainWindow.on_color_brightness_slider_changed)
        self.greenFactorSlider.valueChanged['int'].connect(MainWindow.on_color_brightness_slider_changed)
        self.blueFactorSlider.valueChanged['int'].connect(MainWindow.on_color_brightness_slider_changed)
        self.redFactorLineEdit.editingFinished.connect(MainWindow.on_color_brightness_input_edited)
        self.greenFactorLineEdit.editingFinished.connect(MainWindow.on_color_brightness_input_edited)
        self.blueFactorLineEdit.editingFinished.connect(MainWindow.on_color_brightness_input_edited)
        self.showHistogramsButton.clicked.connect(MainWindow.on_show_histograms_button_clicked)
        self.showScatterPlotsButton.clicked.connect(MainWindow.on_show_scatter_plots_button_clicked)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.loadImageButton.setText(_translate("MainWindow", "load image"))
        self.showHistogramsButton.setText(_translate("MainWindow", "show histograms"))
        self.showScatterPlotsButton.setText(_translate("MainWindow", "show scatter plots"))
        self.redFactorNameLabel.setText(_translate("MainWindow", "Red"))
        self.greenFactorNameLabel.setText(_translate("MainWindow", "Green"))
        self.blueFactorNameLabel.setText(_translate("MainWindow", "Blue"))
        self.redFactorLineEdit.setText(_translate("MainWindow", "1.0"))
        self.greenFactorLineEdit.setText(_translate("MainWindow", "1.0"))
        self.blueFactorLineEdit.setText(_translate("MainWindow", "1.0"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Color brightness"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Color saturation"))

