---
name: Unittest
run-name: compile and unittest cython linalg module
on: [push]

jobs:
  compile_extension_modules_from_cython:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: python3 -m pip install setuptools
      - run: python3 -m pip install Cython
      - run: python3 setup.py build_ext -i
        working-directory: ./image_manipulation/cynalg
      - uses: actions/upload-artifact@v4
        with:
          path: |
            image_manipulation/cynalg/*.so
            image_manipulation/cynalg/*.c
            image_manipulation/cynalg/*.html

  unittest_cynalg_linalg:
    needs: compile_extension_modules_from_cython
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
      - run: python3 -m pip install pytest
      - run: python3 -m pip install numpy
      - run: python3 -m pytest linalg_test.py
        working-directory:: cd test
...
